/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.bot.reminder;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan("org.bot.reminder.config")
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
